	.ORIG X5000

FX	LDI R1, DEGREE 	;R1 IS THE COUNTER
	NOT R1, R1
	ADD R1, R1, #1		
	LD R2, COUNT	
	BRP SAVE
	LDI R1, COEFF	;R1 IS FIRST COEFF
	ST  R1, TEMP	;SAVE FIRST COEFF
SAVE	ADD R1, R1, R2 	;DECREASE COUNTER
	BRZ	END
	LD R3, COEFF	;LOAD R2 WITH FIRST COUNTER POSITION
	LDR R4, R3, #0 	;R4 IS COEFFICIENT	
	ADD R5, R4, #0	;COPY R4
	ADD R6, R0, #0	;COPY R0 INTO R6, R6 IS COUNTER
	BRNP XZER0
	AND R5, R5, #0	;SET R5 TO ZERO AND END MULT
	BRNZP ENDM
XZER0	ADD R5, R5, #0	;MAKE SURE COEFFICIENT ISNT ZERO
	BRNP CZERO 
	AND R5, R5, #0	;SET R5 TO ZERO AND END MULT
	BRNZP ENDM
CZERO	ADD R6, R6, #0	;GRAB X NZP
	BRP NONEG
	NOT R6, R6	;LET R6 COUNTER BE POS	
	BRZ FORONE	;ACCOUNT FOR *1 CASEE
NMULT	ADD R5, R5, R4	;
	ADD R6, R6, #-1	;
	BRP NMULT
FORONE	NOT R5, R5
	ADD R5, R5, #1
	BRNZP ENDM
NONEG	ADD R6, R6, #-1	;DEC COUNT
MULT	ADD R5, R5, R4 	; ADD ITSELF
	ADD R6, R6, #-1
	BRP MULT
ENDM	ADD R2, R2, #1	;INC COUNT
	ADD R3, R3, R2	;GET NEXT COEFF MEM LOCATION
	LDR R6, R3, #0	;GET NEXT COEFF VALUE
	ADD R4, R5, R6	;PUT FIRST (AX+B) VAL INTO R4
	LD R3, COEFF	;GET ORIG COEFF LOCATION
	STR R4, R3, #0	;FOR NEXT COEFF VALUE
	ST R2, COUNT
	NOT R1, R1	;REFLIP R1
	ADD R1, R1, #1	
	BRNZP	FX	;REPEAT	
END 	AND R1, R1, #0	;
	ST R1, COUNT;
	LD R1, TEMP;
	LD R2, COEFF;
	STR R1, R2, #0	;RESET FIRST COEFF
	RET		;R4 HAS VALUE OF FX
	

COUNT	.FILL X0000
DEGREE	.FILL X4003
COEFF	.FILL X4004
TEMP 	.BLKW 1
	
	.END