	.ORIG X3000
	LD	R6, PNT
	AND 	R5, R5, #0
	BR	NFILL
	PNT	.FILL X4000
NFILL	LD	R0, ROCK	; PUSH FIRST ROW ONTO STACK
	BR	SFILL
	ROCK	.FILL X006F	
SFILL	JSR	PUSH		; X3FFF -> X3FFD
	JSR	PUSH
	JSR	PUSH
	AND	R0, R0, #0
	JSR	PUSH		; X3FFC

	LD	R0, ROCK	; PUSH SECOND ROW ONTO STACK
	JSR	PUSH		; X3FFB -> X3FF7
	JSR	PUSH
	JSR	PUSH
	JSR	PUSH
	JSR	PUSH
	AND	R0, R0, #0
	JSR	PUSH		; X3FF6

	LD	R0, ROCK	; PUSH THIRD ROW ONTO STACK
	JSR	PUSH		; X3FF5 -> X3FEE
	JSR	PUSH
	JSR	PUSH
	JSR	PUSH
	JSR	PUSH
	JSR	PUSH
	JSR	PUSH
	JSR 	PUSH
	AND	R0, R0, #0
	JSR	PUSH		; X3FED
	BR 	RAW

BOARD	LD	R0, LF
	TRAP	X21
RAW	LEA 	R0, ROWA
	TRAP 	X22
	LD	R0, ROW1
	TRAP	X22
	LD	R0, LF
	TRAP	 X21

	LEA 	R0, ROWB
	TRAP 	X22
	LD	R0, ROW2
	TRAP	X22
	LD	R0, LF
	TRAP 	X21

	LEA 	R0, ROWC
	TRAP 	X22
	LD	R0, ROW3
	TRAP	X22
	LD	R0, LF
	TRAP 	X21

	ADD	R5, R5, #1
	BRP	INP1
	BR	INP2

INP1	ADD	R5, R5, #-1
I1	LEA 	R0, P1
	TRAP	X22
	BR	DNE
INP2	ADD	R5, R5, #1
I2	LEA	R0, P2
	TRAP	X22
DNE	TRAP	X20
	TRAP	X21
	ADD	R2, R0, #0	; ROW INTO R2 (A, B, OR C)
	TRAP	X20
	TRAP	X21
	ADD	R3, R0, #0	; NUMBER OF ROCKS INTO R3
	LD	R0, LF
	TRAP	X21

CHECK	AND	R1, R1, #0
	LD	R4, NEGA
	ADD	R4, R2, R4
	BRZ	GOODA
	LD 	R4, NEGB
	ADD	R4, R2, R4
	BRZ	GOODB
	LD	R4, NEGC
	ADD	R4, R2, R4
	BRZ	GOODC
INV	LEA	R0, INVAL
	TRAP	X22
	LD 	R0, LF
	TRAP	X21
	ADD	R0, R5, #0
	BRZ	I1
	BR	I2

GOODA	LD	R0, ROW1
	BR	GO
GOODB	LD	R0, ROW2
	BR	GO
GOODC	LD	R0, ROW3
	BR	GO
GO	LDR	R4, R0, #0
	BRZ	ENDC
	ADD	R1, R1, #-1	;R1 HAS NUMBER OF ROCKS IN ROW
	ADD	R0, R0, #1
	BR	GO

ENDC	LD	R0, HTOD
	ADD	R3, R3, R0	;CONVERT R3 TO DECIMAL VAL		
	ADD	R0, R1, R3
	BRP	INV
	ADD	R3, R3, #0
	BRNZ	INV
	AND	R1, R1, #0	;PERFORM MOVE
	LD	R4, NEGA
	ADD	R4, R2, R4
	BRZ	AROW
	LD 	R4, NEGB
	ADD	R4, R2, R4
	BRZ	BROW
	LD	R4, NEGC
	ADD	R4, R2, R4
	BRZ	CROW

AROW	LD	R1, ROW1	;CHANGE POINTER FOR ROCKS
	ADD	R1, R3, R1
	ST	R1, ROW1
	BR	GAMEO
BROW	LD	R1, ROW2	;CHANGE POINTER FOR ROCKS
	ADD	R1, R3, R1
	ST	R1, ROW2
	BR	GAMEO
CROW	LD	R1, ROW3	;CHANGE POINTER FOR ROCKS
	ADD	R1, R3, R1
	ST	R1, ROW3
	BR	GAMEO

GAMEO	ADD	R5, R5, #-1
	ST	R1, SAVER1
	ST	R2, SAVER2
	ST	R3, SAVER3
	ST	R4, SAVER4
	ST	R5, SAVER5
	ST	R6, SAVER6
	LD	R1, END1
	LD	R2, END2
	LD	R3, END3
	LD	R4, ROW1
	LD	R5, ROW2
	LD	R6, ROW3
	ADD	R1, R4, R1
	BRZ	N2
	BR 	GAMED
N2	ADD	R2, R5, R2
	BRZ	N3
	BR	GAMED
N3	ADD	R3, R6, R3
	BRZ	GAME
GAMED	LD	R1, SAVER1
	LD	R2, SAVER2
	LD	R3, SAVER3
	LD	R4, SAVER4
	LD	R5, SAVER5
	LD	R6, SAVER6
	BR	BOARD	

GAME	LD 	R0, LF
	TRAP	X21
	LD	R5, SAVER5
	BRZ	OWIN
	LEA	R0, BWIN
	TRAP	X22
	BR 	GG
OWIN	LEA	R0, AWIN
	TRAP	X22
GG	HALT

PUSH	ST	R2, SAVE2
	ST	R1, SAVE1
	LD 	R1, MAX
	ADD	R2, R6, R1
	BRZ	FEXIT
	ADD	R6, R6, #-1
	STR	R0, R6, #0
SEXIT	LD	R1, SAVE1
	LD	R2, SAVE2
	AND	R5, R5, #0
	RET
FEXIT	LD	R1, SAVE1
	LD	R2, SAVE2
	AND	R5, R5, #0
	ADD 	R5, R5, #1
	RET

LF	.FILL X000A
ORANGE	.FILL X-0030
SAVER1	.BLKW 1
SAVER2	.BLKW 2
SAVER3	.BLKW 3
SAVER4	.BLKW 4
SAVER5	.BLKW 5
SAVER6	.BLKW 6
END1	.FILL X-4000
END2	.FILL X-3FFC
END3	.FILL X-3FF6
ROW1	.FILL X3FFD		; LOCATION OF FIRST ROW
ROW2	.FILL X3FF7		; LOCATION OF SECOND ROW
ROW3	.FILL X3FEE		; LOCATION OF THIRD ROW
BASE	.FILL	XC001
MAX	.FILL	XC020
SAVE1	.BLKW	1
SAVE2	.BLKW	1
HTOD	.FILL	X-0030
NEGA	.FILL	X-0041
NEGB	.FILL	X-0042
NEGC	.FILL	X-0043
INVAL	.STRINGZ "Invalid move. Try again."
ROWA	.STRINGZ "ROW A: "
ROWB	.STRINGZ "ROW B: "
ROWC	.STRINGZ "ROW C: "
P1	.STRINGZ "Player 1, choose a row and number of rocks: "
P2	.STRINGZ "Player 2, choose a row and number of rocks: "
AWIN	.STRINGZ "Player 1 Wins."
BWIN	.STRINGZ "Player 2 Wins."


	.END